name: Nix CI

on:
  push:
    branches:
      - monarchic
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  nix-ci:
    uses: monarchic-langs/.github/.github/workflows/nix-ci.yml@main
    with:
      publish_cache: ${{ github.ref == 'refs/heads/monarchic' }}
    secrets:
      MONARCHIC_GITHUB_PAT: ${{ secrets.MONARCHIC_GITHUB_PAT }}
