name: Prepare Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  actions: read
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: monarchic-langs/.github/.github/workflows/github-release-draft.yml@main
    with:
      default_branch: monarchic
      release_notes_command: node ./scripts/release-notes.mjs "$GITHUB_REF_NAME"
    secrets: inherit
