name: Release

on:
  push:
    tags: ['v*.*.*']
  release:
    types: [published]

permissions:
  actions: read
  contents: read
  id-token: write

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  publish:
    uses: monarchic-langs/.github/.github/workflows/release-command.yml@main
    with:
      default_branch: monarchic
      pnpm_version: 9.6.0
      install_command: pnpm install --frozen-lockfile
      build_command: pnpm -r run build
      release_command: |
        pnpm --recursive --filter='!vscode-tailwindcss' publish --tag latest --access public --no-git-checks
        cd packages/vscode-tailwindcss
        pnpm run publish -p "$VSCODE_TOKEN"
    secrets:
      VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
